#pragma once
#define WIN32_LEAN_AND_MEAN
#define _CRT_SECURE_NO_WARNINGS
#include <string>
#include <windows.h>
#include <iostream>
#include <array>
#include <stdlib.h>
#include <stdio.h>
#include <stdexcept>
#include <malloc.h>
#include <memory.h>
#include <memory>
#include <tchar.h>
#include <chrono>
#include <vector>
#include <algorithm>
#include <filesystem>